repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.11.0  # CURRENT_TAG/COMMIT_HASH
    hooks:
      - id: jupytext
        args: [ --from, ipynb, --to, "py:percent" ]



  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.7.4'  # Use the sha / tag you want to point at
    hooks:
      - id: pylint
        types: [ python ]
        args:
          [
              "-rn",
              "-sn",
              "--rcfile=.configs/.pylintrc",
              "--load-plugins=pylint.extensions.docparams",
          ]
        # disabled plugins: pylint.extensions.mccabe

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args: [ "--ignore-missing-imports", "--scripts-are-modules" ]
        require_serial: true
        additional_dependencies: [ ]
