repos:
  - repo: local
    hooks:
#      - id: jupytext
      #        name: jupytext
      #        entry: jupytext --from ipynb --to py:percent --pre-commit
      #        pass_filenames: false
      #        language: system
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]