repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.11.0
    hooks:
      - id: jupytext
        args: [ --from, ipynb, --to, "py:percent" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.7.4'
    hooks:
      - id: pylint
        types: [ python ]
        args:
          [
              "-rn",
              "-sn",
              "--rcfile=.pylintrc",
              "--load-plugins=pylint.extensions.docparams",
          ]
        # disabled plugins: pylint.extensions.mccabe

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args: [ "--ignore-missing-imports", "--scripts-are-modules" ]
        require_serial: true
        additional_dependencies: [ ]

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [ commit ]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
      - id: nbstripout

#  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
#    rev: v4.1.0
#    hooks:
#      - id: commitlint
#        stages: [ commit-msg ]
#        additional_dependencies: [ '@commitlint/config-conventional' ]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
    -   id: gitlint
