repos:
  - repo: local
    hooks:
      #sdfsd
      #sdfsd
      #      - id: jupytext
      #        name: jupytext
      #        entry: jupytext
      #        language: conda
      #        args: [ --sync ]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]