# base environment for my utils
name: test
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  # Core scientific python
  - numpy
  - pandas

  - jupyter
  - notebook


  - jupytext
  - pre-commit
  - pip:
      - sqlfluff  # sql linter
      - pylint  # python linter
