[tool.mypy]
python_version = "3.7"
show_error_context = true
show_column_numbers = true
pretty = true
show_error_codes = true

disallow_any_generics = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_reexport = true
#disallow_subclassing_any = true
#disallow_untyped_calls = true
#disallow_any_unimported = true
#warn_unused_configs = true
# warn_unused_ignores = true  # purposely disabled
#strict_equality = true

#[[tool.mypy.overrides]]  # example of module disable for mypy
#module = "google.oauth2.*"
#ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
python_files = [
  "test_*.py",
  "example_*.py"
]


[tool.coverage.run]
omit = [
  "setup.py",
  "*/notebooks/*",
  "*/main.py",
  "common/*",
  "module/*",
  "*/__init__.py"]
data_file = ".cache/.coverage"

# need to `pip install pytest pytest-cov converage[toml] pytest-xdist
# from root dir:
# pytest -n 3 --rootdir=. . --cov=.  --cov-fail-under=80
